In [3]:
# EX.0.1.2.Sauer


x = -1/2

a = ((6 * x - 2) * x - 3) * x + 7
b = ((((8 * x - 1) * x - 3) * x + 1) * x - 3) * x + 1
c = ((((( x ) * 4 * x - 2) * x) * x) * x - 2) * x + 4

#double_check_a = (6 * x ** 3) - (2 * x ** 2) - ( 3 * x) + 7
#double_check_b = (8 * x ** 5) - (x ** 4) - ( 3 * x ** 3) + (x ** 2) - (3 * x) + 1
#double_check_c = (4 * x ** 6) - (2 * x ** 4) - ( 2 * x) + 4

print(a, b, c)
#print(double_check_a, double_check_b, double_check_c)

7.25 2.8125 4.9375
7.25 2.8125 4.9375


In [4]:
# EX.0.1.6.Sauer
# Utilizing the nested multiplication algorithm to not 'waste' multiplication
# operations when they aren't neccesary. Likewise, using powers of two to create
# a more logarithmic growth to reach exponents compared to linearly increasing.
# Checking work along the way to ensure the nesting is performed correctly.

import numpy as np

# a. p(x) = a0 + a5 x^5 + a10 x^10 + a15 x^15

# reference evaluation
a00 = -13; a05 = 26; a10 = 94; a15 = -2;
x = np.array( [ -2, -1, 0, 1, 2 ] );
px0 = a00 + a05 * ( x ** 5 ) + a10 * ( x ** 10 ) + a15 * ( x ** 15 )
print( px0 )

# our implementation
x2 = x * x
x4 = x2 * x2
x5 = x4 * x
px1 = a00 + x5 * ( a05 + x5 * ( a10 + a15 * x5 ) )
print( px1 )
# 6 multiplications, 3 additions, 0 power operator

print( np.max( px1 - px0 ) )




# b. p(x) = a07 x^7  + a12 x^12 + a17 x^17 + a22 x^22 + a27 x^27
#         = x^7 (a07 + a05 x^05 + a10 x^10 + a15 x^15 + a20 x^20)

# reference evaluation
a07 = -17; a12 = 36; a17 = -24; a22 = -3; a27 = 4;
x = np.array( [ -2, -1, 0, 1, 2 ] );
px0 = a07 * ( x ** 7 ) + a12 * ( x ** 12 ) + a17 * ( x ** 17 ) + a22 * ( x ** 22 ) + a27 * ( x ** 27 )
print( px0 )

# our implementation
x2 = x * x
x4 = x2 * x2
x5 = x4 * x
x7 = x5 * x2
px1 = x7 * ( a07 + x5 * ( a12 + x5 * ( a17 + x5 * ( a22 + x5 * a27 ) ) ) )
print(px1)
# 9 multiplications, 4 additions, 0 power operator

print( np.max( px0 - px1 ) )


[160947     57    -13    105  31539]
[160947     57    -13    105  31539]
0
[-546158464         70          0         -4  521287552]
[-546158464         70          0         -4  521287552]
0


In [1]:
# CP.0.1.2.Sauer

import numpy as np
np.set_printoptions(precision=3,suppress=False)

def polyval_nested( c, x ):
  d = np.size(c)
  px = c[ d-1 ]
  for i in range( d-2, -1, -1 ):
    px = px * + x + c[i]
  return px

d = 99
x = 1.00001

c = np.ones( [d+1], dtype=np.float64 )

for i in range(0, d + 1):
  if i % 2 == 0:
    pass
  else:
    c[i] = -1


px1 = polyval_nested( c, x )
print( px1 )

px2 = np.polyval( np.flip(c), x )
print( px2 )

px3 = ( 1 - (x ** 100) ) / ( 1 + x )
print( px3 )

print( np.abs( ( px1 - px3 ) / px3 ) )

-0.0005002450796476321
-0.0005002450796476321
-0.0005002450796474608
3.424400363386547e-13


In [15]:
# EX.0.2.8.Sauer
# Binary to base 10

x = ( 0b11011 )
print( x )

x = ( 0b110111001 ) * ( 2 ** (-3) )
print( x )

x = ( 0b111001001001001 ) * ( 2 ** (-12) )
print( x )
print ( 1/7 )

x = ( 0b1010010101010101 ) * ( 2 ** (-12) )
print( x )

x = ( 0b101111010101010101 ) * ( 2 ** (-13) )
print( x )

x = ( 0b1111010001001001001001001001001001 ) * ( 2 ** (-30) )
print( x )

27
55.125
7.142822265625
0.14285714285714285
10.333251953125
23.6666259765625
15.267857142724097


In [10]:
# EX.0.3.7

import struct
def double_to_hex(f):
  return hex(struct.unpack('<Q', struct.pack('<d', f))[0])

print( double_to_hex(  16.) )
print( double_to_hex( 130.) )
print( double_to_hex( 0.25) )
print( double_to_hex( 1./7. ) )
print( double_to_hex( 4./7. ) )
print( double_to_hex( 0.01 ) )
print( double_to_hex( -1./100. ) )
print( double_to_hex( -2./100. ) )

print(1 + 2 ** -51 + 2 ** -52 +  2 ** -54 - 1)
print(2 ** -51 + 2 ** -52)

0x4030000000000000
0x4060400000000000
0x3fd0000000000000
0x3fc2492492492492
0x3fe2492492492492
0x3f847ae147ae147b
0xbf847ae147ae147b
0xbf947ae147ae147b
6.661338147750939e-16
6.661338147750939e-16


In [10]:
import numpy as np

# double check and calculation
coefficients = [1, 3, -8 ** (-14)]
roots = np.roots(coefficients)
print("Roots of the polynomial:", roots)

print( -1 * ( 3 + ( 9 - 4 * ( -8  ** -14) ) ** 0.5 ) / 2)

print( -1 * (2 * ( -8  ** -14) / (3 + ( 9 - 4 * ( -8  ** -14) ) ** 0.5)))

Roots of the polynomial: [-3.00000000e+00  7.57912251e-14]
-3.0000000000000755
7.579122514774211e-14
